var Consts = {
	SCREEN_WIDTH: 1920,
	SCREEN_HEIGHT: 650,
	BLOCK_SIZE: 50,
	CHARACTER_RADIUS: 20,
	TYPES: {
		AIR : 0,
		DIRT : 1,
		HOLLOW : 2,
		CREATED : 3,
		CREATEDAIR : 4,
		BEDROCK : 5
	},
	MINIMAP_WIDTH: 500,
	MINIMAP_HEIGHT: 200,
	GRAVITY: 400,
	SPELLCOST: 1,
	BLOCKSFORONESPELLCOST: 10,
	TIMEBETWEENCALL : 10,
	CANVASWIDTH : 4090
};

Object.freeze(Consts);