define(function() {
	'use strict';
	
	var Consts = {
		SCREEN_WIDTH: 1920,
		SCREEN_HEIGHT: 650,
		BLOCK_SIZE: 50,
		CHARACTER_RADIUS: 20,
		TYPES: {
			AIR : 0,
			GROUND_TOP : 1,
			GROUND : 2,
			WALL : 3,
			SPIKE : 4,
			DESTRUCTIBLE_WALL: 5,
			ENEMY_LEFT : 6,
			ENEMY_RIGHT : 7,
			GENERAL_LEFT : 8,
			GENERAL_RIGHT : 9
		},
		MINIMAP_WIDTH: 500,
		MINIMAP_HEIGHT: 200,
		GRAVITY: 400,
		SPELLCOST: 1,
		BLOCKSFORONESPELLCOST: 10,
		TIMEBETWEENCALL : 10,
		CANVASWIDTH : 4090
	};

	return Consts;
}());
